### ISSUE TITLE
Comment on example of 'native syntax' in README

### ISSUE THREAD

**Issue by PeteHaitch** [martijnvanattekum/cleanse#1]
Hi @martijnvanattekum,

I saw **cleanse** submitted to Bioconductor and it prompted me to take a quick look at the package.

This is just a comment on something that caught my eye in the `README.md`, and this is partly a matter of perhaps personal coding style, but an example of 'native syntax' struck me as a bit 'non-native'/'unnatural' (for want of a better word):

```r
# From README.md: "Using native syntax"
coldata <- colData(se) 
indices <- which(coldata$time == 4) 
se[,indices] 
```

I think most 'base R-centric Bioconductor' users would use the simpler:

```r
se[, which(se$time == 4)]
```

Or, if you know there are no NAs, then the even simpler:

```r
se[, se$time == 4]
```

Anyway, it's a minor thing, but when comparing 'base' vs. 'tidy' approaches I think it pays to try to write both versions as 'natively'/'naturally' as possible.

Cheers,
Pete

**Comment by martijnvanattekum** [comment]
You are right that this syntax can be more easily written by using the fact that $-extraction from an se internally dispatches the extraction to its coldata. AFAIK, this extraction trick does not work for rowdata though.
I have now adapted the example to reflect your suggestions and added one more step to shift focus more on pipe vs non-pipe instead of efficient vs inefficient. It looks better now, thanks!

**Comment by PeteHaitch** [comment]
Thanks for being receptive to the suggestion.
You're right that `$`-extraction from an se only applies to _colData_.

BTW I like the prospect of what you mentioned in the review issue that in comparison to **tidySummarizedExperiment** that "cleanse stays closer to the original se dimensions (wide format)".
